baseurl = "https://www.aaronyaosmith.com"
uglyurls = true
builddrafts = true
languageCode = "en-us"
title = "Aaron Yao-Smith"
theme = "hugo-goa"
author = "Aaron Yao-Smith"
canonifyurls = true
googleAnalytics = "UA-120521681-2"
enableRobotsTXT = true

[params]
    author = "Aaron Yao-Smith"
    intro = "Cornell University '21"
    description = "software engineer intern @ [**CoinFund**](https://coinfund.io)\n\naaron@coinfund.io\n\naaron@aaronyaosmith.com\n\n(607) 288-2756\n\n**resume:** [<u>PDF</u>](/resume.pdf)"
    authorimage = "headshot.jpg"
    dateformat = "Jan 2, 2006"
    
[params.meta]
    description = "Aaron Yao-Smith"
    keywords = "Aaron Yao-Smith, Aaron, Yao-Smith, Yao, Smith, Yaosmith, Aaron Yaosmith, aaronyaosmith, Cornell, computer science, 2021, Ithaca, Boston, developer"

[params.social]
    github = "aaronyaosmith"
    linkedin = "aaronyaosmith"
    
[params.extra]
    copyright = "© 2019. Aaron Yao-Smith. All Rights Reserved."
    poweredby = true
    
#[[menu.main]]
#    name = "blog"
#    url = "/blog/"
    weight = 1
[[menu.main]]
    name = "about"
    url = "/about/index.html"
    weight = 2
