baseurl = "http://aaronyaosmith.github.io"
builddrafts = true
languageCode = "en-us"
title = "Aaron Yao-Smith"
theme = "hugo-goa"
author = "Aaron Yao-Smith"
canonifyurls = true
googleAnalytics = "UA-120521681-2"

[params]
    author = "Aaron Yao-Smith"
    intro = "Cornell University"
    description = "hi I'm Aaron nice to meet you"
    authorimage = "headshot.jpg"
    dateformat = "Jan 2, 2006"
    
[params.meta]
    description = "Aaron Yao-Smith"
    keywords = "Aaron, Yao-Smith, Cornell, developer"

[params.social]
    github = "aaronyaosmith"
    linkedin = "aaronyaosmith"
    email = "aaron@aaronyaosmith.com"

[params.extra]
    copyright = "© 2018. Aaron Yao-Smith. All Rights Reserved."
    poweredby = true
    
#[[menu.main]]
#    name = "blog"
#    url = "/blog/"
    weight = 1
[[menu.main]]
    name = "about"
    url = "/about/"
    weight = 2
