baseurl = "http://aaronyaosmith.github.com"
languageCode = "en-us"
title = "Aaron Yao-Smith"
theme = "saito-boilerplate"

canonifyurls = true
paginate = 3
# publishDir = "docs" # if you use GitHub to deploy
# disqusShortname = "yourdisqusshortname"
googleAnalytics = "UA-120521681-2"

[params]
    description = "Aaron Yao-Smith"
    keywords = "Aaron, Yao-Smith"
    images = [""]

[author]
    name = "Aaron Yao-Smith"

[social]
    twitter = ""
    facebook = ""
    facebook_admin = ""
    linkedin = "aaronyaosmith"
    instagram = ""
    googleplus = ""
    github = "aaronyaosmith"
    gitlab = ""
    pinterest = ""
    tumblr = ""
    vimeo = ""
    youtube = ""

# if you want markdown WYSIWYG line break
[blackfriday]
    extensions = ["hardLineBreak"]

# main menu
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1
[[menu.main]]
    name = "Works"
    url = "/works-index/"
    weight = 2
[[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 3

# Add footer contents here
[[params.footer]]
    name = ""
    url = false
[[params.footer]]
    name = "aaron@aaronyaosmith.com"
    url = "mailto:"
