baseurl = "https://www.aaronyaosmith.com"
uglyurls = true
builddrafts = true
languageCode = "en-us"
title = "Aaron Yao-Smith"
theme = "hugo-goa"
author = "Aaron Yao-Smith"
canonifyurls = true
googleAnalytics = "UA-120521681-2"
enableRobotsTXT = true

[params]
    author = "Aaron Yao-Smith"
    intro = "Cornell University"
    description = "Research assistant (part-time), [Singer Group](https://www.singerlab.website/)\n\n[Department of Biostatistics and Computational Biology](https://www.dana-farber.org/research/departments-centers-and-labs/departments-and-centers/department-of-biostatistics-and-computational-biology/), [Dana-Farber Cancer Institute](https://www.dana-farber.org/)\n\naaron -at- aaronyaosmith -dot- com\n\n(607) 288-2756"
    authorimage = "headshot.jpg"
    dateformat = "Jan 2, 2006"
    
[params.meta]
    description = "Aaron Yao-Smith"
    keywords = "Aaron Yao-Smith, Yao-Smith, Cornell, computer science, 2021, Ithaca, Boston, developer"

[params.social]
    github = "aaronyaosmith"
    linkedin = "aaronyaosmith"
    
[params.extra]
    copyright = "© 2018. Aaron Yao-Smith. All Rights Reserved."
    poweredby = true
    
#[[menu.main]]
#    name = "blog"
#    url = "/blog/"
    weight = 1
[[menu.main]]
    name = "about"
    url = "/about/index.html"
    weight = 2
